#!/usr/bin/env python3
"""Generate PyLab catalogs for workbook chapters 2 through 4."""

from __future__ import annotations

import ast, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def a(name, type_, description, default=None): return (name, type_, description, default)
def c(name, call, expected, approx=False): return (name, call, expected, approx)
def s(number, slug, title, args, ret, summary, rules, example, output, cases, concepts, difficulty="Beginner", imports=(), raises=()):
    return locals()


CONDITIONALS = [
s("2.1","even_or_odd","Even or Odd",[a("number","int","Integer to classify.")],"str","Classify an integer by parity.","Return 'even' when number is divisible by 2 and 'odd' otherwise.","even_or_odd(17)","'odd'",[c("odd","even_or_odd(17)","'odd'"),c("even","even_or_odd(24)","'even'"),c("zero","even_or_odd(0)","'even'")],["conditionals","modulo"]),
s("2.2","dog_years","Dog Years",[a("human_years","float","Non-negative age in human years.")],"float","Convert a dog's age from human years to dog years.","The first two human years count as 10.5 dog years each; every additional year counts as 4 dog years. Raise ValueError for a negative age.","dog_years(5)","33.0",[c("puppy","dog_years(1)","10.5"),c("two years","dog_years(2)","21.0"),c("adult","dog_years(5)","33.0")],["piecewise formulas","conditionals"],raises=(("ValueError","If human_years is negative."),)),
s("2.3","letter_kind","Vowel, Consonant, or Sometimes",[a("letter","str","Single alphabetic character to classify.")],"str","Classify a letter by its vowel behavior.","Return 'vowel' for a, e, i, o, or u; 'sometimes' for y; and 'consonant' for every other letter. Ignore case.","letter_kind('Y')","'sometimes'",[c("vowel","letter_kind('A')","'vowel'"),c("y","letter_kind('y')","'sometimes'"),c("consonant","letter_kind('q')","'consonant'")],["strings","membership","conditionals"]),
s("2.4","shape_name","Name a Polygon",[a("sides","int","Number of polygon sides.")],"str","Name a polygon from its number of sides.","Recognize 3 through 10 sides as triangle, quadrilateral, pentagon, hexagon, heptagon, octagon, nonagon, and decagon. Return 'unsupported' otherwise.","shape_name(6)","'hexagon'",[c("triangle","shape_name(3)","'triangle'"),c("octagon","shape_name(8)","'octagon'"),c("unsupported","shape_name(12)","'unsupported'")],["lookup","conditionals"]),
s("2.5","month_days","Days in a Month",[a("month","str","English month name.")],"int | tuple[int, int]","Report the possible number of days in a month.","Return 31 or 30 for fixed-length months. Return (28, 29) for February because no year is supplied. Match month names case-insensitively.","month_days('February')","(28, 29)",[c("long month","month_days('January')","31"),c("short month","month_days('September')","30"),c("February","month_days('february')","(28, 29)")],["calendar","conditionals"]),
s("2.6","sound_description","Sound Level",[a("decibels","float","Sound level in decibels.")],"str","Compare a sound level with familiar reference noises.","Exact levels are quiet room 40, alarm clock 70, gas lawnmower 106, and jackhammer 130. Between references, describe it as 'between X and Y'; below 40 or above 130 returns 'outside range'.","sound_description(70)","'alarm clock'",[c("exact","sound_description(70)","'alarm clock'"),c("between","sound_description(80)","'between alarm clock and gas lawnmower'"),c("outside","sound_description(20)","'outside range'")],["ranges","conditionals"]),
s("2.7","triangle_kind","Triangle Type",[a("a","float","First side length."),a("b","float","Second side length."),a("c","float","Third side length.")],"str","Classify a triangle from its side lengths.","Return 'equilateral' for three equal sides, 'isosceles' for exactly two equal sides, and 'scalene' otherwise. Inputs form a valid triangle.","triangle_kind(5, 5, 3)","'isosceles'",[c("equilateral","triangle_kind(4,4,4)","'equilateral'"),c("isosceles","triangle_kind(5,5,3)","'isosceles'"),c("scalene","triangle_kind(3,4,5)","'scalene'")],["comparisons","geometry"]),
s("2.8","note_frequency","Musical Note Frequency",[a("note","str","Note name from C0 through B8.")],"float","Calculate the frequency of a named musical note.","Use C4=261.63 Hz and fourth-octave offsets D4=293.66, E4=329.63, F4=349.23, G4=392.00, A4=440.00, B4=493.88. Multiply by 2^(octave-4).","note_frequency('A4')","440.0",[c("concert A","note_frequency('A4')","440.0",True),c("A5","note_frequency('A5')","880.0",True),c("C3","note_frequency('C3')","130.815",True)],["music","exponents","parsing"],"Intermediate"),
s("2.9","frequency_note","Frequency to Note",[a("frequency","float","Frequency in hertz."),a("tolerance","float","Maximum accepted difference in hertz.","1.0")],"str | None","Find the nearest fourth-octave note within a tolerance.","Compare with these frequencies in hertz: C4=261.63, D4=293.66, E4=329.63, F4=349.23, G4=392.00, A4=440.00, and B4=493.88. Return the note name when its absolute difference is at most tolerance; otherwise return None.","frequency_note(439.5)","'A4'",[c("near A","frequency_note(439.5)","'A4'"),c("exact C","frequency_note(261.63)","'C4'"),c("unknown","frequency_note(450)","None")],["nearest value","tolerance","conditionals"],"Intermediate"),
s("2.10","banknote_person","Faces on U.S. Money",[a("denomination","int","U.S. banknote value in dollars.")],"str | None","Identify the historical figure shown on a U.S. banknote.","Use this complete mapping: $1 George Washington, $2 Thomas Jefferson, $5 Abraham Lincoln, $10 Alexander Hamilton, $20 Andrew Jackson, $50 Ulysses S. Grant, and $100 Benjamin Franklin. Return None for unsupported denominations.","banknote_person(20)","'Andrew Jackson'",[c("twenty","banknote_person(20)","'Andrew Jackson'"),c("two","banknote_person(2)","'Thomas Jefferson'"),c("unknown","banknote_person(25)","None")],["mapping","currency"]),
s("2.11","holiday_name","Canadian Holiday",[a("month","int","Month number from 1 through 12."),a("day","int","Day of month.")],"str | None","Identify one of three fixed-date Canadian holidays.","Return 'New Year’s Day' for January 1, 'Canada Day' for July 1, and 'Christmas Day' for December 25. Return None for other dates.","holiday_name(7, 1)","'Canada Day'",[c("new year","holiday_name(1,1)","'New Year’s Day'"),c("Canada Day","holiday_name(7,1)","'Canada Day'"),c("ordinary date","holiday_name(3,14)","None")],["dates","conditionals"]),
s("2.12","chess_square_color","Chessboard Colour",[a("square","str","Chess coordinate such as a1 or h8.")],"str","Determine whether a chessboard square is black or white.","Columns a through h and rows 1 through 8 alternate colours; a1 is black. Match the column case-insensitively.","chess_square_color('d5')","'white'",[c("origin","chess_square_color('a1')","'black'"),c("neighbor","chess_square_color('b1')","'white'"),c("another square","chess_square_color('d5')","'white'")],["parity","coordinates"]),
s("2.13","season","Season from Date",[a("month","int","Month number."),a("day","int","Day of month.")],"str","Determine the astronomical season for a date.","For this exercise, use these fixed boundaries: spring begins March 20, summer June 21, fall September 22, and winter December 21. Dates before March 20 are also winter.","season(10, 1)","'fall'",[c("spring boundary","season(3,20)","'spring'"),c("summer","season(7,1)","'summer'"),c("fall","season(10,1)","'fall'"),c("winter","season(1,15)","'winter'")],["dates","ordered boundaries"]),
s("2.14","zodiac_sign","Western Zodiac Sign",[a("month","int","Birth month number."),a("day","int","Birth day.")],"str","Determine a Western astrological sign from a birth date.","Use the standard boundaries: Capricorn Dec22-Jan19, Aquarius Jan20-Feb18, Pisces Feb19-Mar20, Aries Mar21-Apr19, Taurus Apr20-May20, Gemini May21-Jun20, Cancer Jun21-Jul22, Leo Jul23-Aug22, Virgo Aug23-Sep22, Libra Sep23-Oct22, Scorpio Oct23-Nov21, Sagittarius Nov22-Dec21.","zodiac_sign(8, 1)","'Leo'",[c("Aries boundary","zodiac_sign(3,21)","'Aries'"),c("Leo","zodiac_sign(8,1)","'Leo'"),c("Capricorn","zodiac_sign(1,1)","'Capricorn'")],["dates","ranges"],"Intermediate"),
s("2.15","chinese_zodiac","Chinese Zodiac Animal",[a("year","int","Gregorian year.")],"str","Return the Chinese zodiac animal associated with a year.","Use year modulo 12 with the sequence Monkey, Rooster, Dog, Pig, Rat, Ox, Tiger, Hare, Dragon, Snake, Horse, Sheep for remainders 0 through 11.","chinese_zodiac(2000)","'Dragon'",[c("dragon","chinese_zodiac(2000)","'Dragon'"),c("rat","chinese_zodiac(2020)","'Rat'"),c("tiger","chinese_zodiac(2022)","'Tiger'")],["modulo","cycles"]),
s("2.16","earthquake_description","Earthquake Magnitude",[a("magnitude","float","Richter magnitude.")],"str","Classify an earthquake by Richter magnitude.","Use micro below 2.0, very minor below 3.0, minor below 4.0, light below 5.0, moderate below 6.0, strong below 7.0, major below 8.0, great below 10.0, and meteoric at least 10.0.","earthquake_description(6.4)","'strong'",[c("micro","earthquake_description(1.5)","'micro'"),c("moderate","earthquake_description(5.5)","'moderate'"),c("great","earthquake_description(8.2)","'great'")],["numeric ranges","conditionals"]),
s("2.17","quadratic_roots","Quadratic Roots",[a("a","float","Quadratic coefficient."),a("b","float","Linear coefficient."),a("c","float","Constant coefficient.")],"tuple[float, ...]","Calculate the real roots of a quadratic equation.","For a*x^2+b*x+c=0, use discriminant b^2-4ac. Return (), one repeated root, or two roots in ascending order. a is non-zero.","quadratic_roots(1, -3, 2)","(1.0, 2.0)",[c("two roots","quadratic_roots(1,-3,2)","(1.0,2.0)"),c("one root","quadratic_roots(1,2,1)","(-1.0,)"),c("no real roots","quadratic_roots(1,0,1)","()")],["quadratics","discriminant","square roots"],"Intermediate",("import math",)),
s("2.18","grade_points","Letter Grade to Points",[a("grade","str","Supported letter grade.")],"float","Convert a letter grade to grade points.","Use A+=4.0, A=4.0, A-=3.7, B+=3.3, B=3.0, B-=2.7, C+=2.3, C=2.0, C-=1.7, D+=1.3, D=1.0, and F=0.0. Raise ValueError otherwise.","grade_points('B+')","3.3",[c("A","grade_points('A')","4.0"),c("B plus","grade_points('B+')","3.3"),c("F","grade_points('F')","0.0")],["lookup","grades"],raises=(("ValueError","If grade is unsupported."),)),
s("2.19","letter_grade","Points to Letter Grade",[a("points","float","Numeric grade points.")],"str","Convert grade points to the nearest letter grade.","Use these complete lower boundaries: 4.0 A+, 3.85 A, 3.50 A-, 3.15 B+, 2.85 B, 2.50 B-, 2.15 C+, 1.85 C, 1.50 C-, 1.15 D+, 0.50 D, and F below 0.50. Values between exact grade points therefore round to the nearest letter grade.","letter_grade(3.15)","'B+'",[c("A plus","letter_grade(4.0)","'A+'"),c("B plus","letter_grade(3.2)","'B+'"),c("F","letter_grade(0.2)","'F'")],["ranges","grades"],"Intermediate"),
s("2.20","employee_rating","Employee Assessment",[a("rating","float","Employee performance rating."),a("base_raise","float","Dollar amount multiplied by rating.","2400.0")],"tuple[str, float]","Describe an employee rating and calculate the raise.","Only 0.0, 0.4, and values at least 0.6 are valid. They are unacceptable, acceptable, and meritorious. Raise ValueError for any other rating.","employee_rating(0.8)","('meritorious', 1920.0)",[c("unacceptable","employee_rating(0.0)","('unacceptable',0.0)"),c("acceptable","employee_rating(0.4)","('acceptable',960.0)"),c("meritorious","employee_rating(0.8)","('meritorious',1920.0)")],["validation","currency"],raises=(("ValueError","If rating is not an allowed value."),)),
s("2.21","visible_color","Visible-Light Colour",[a("wavelength_nm","float","Wavelength in nanometres.")],"str | None","Classify a visible-light wavelength by colour.","Use violet 380-450, blue 450-495, green 495-570, yellow 570-590, orange 590-620, and red 620-750 nm. Return None outside the visible range; shared boundaries belong to the later band.","visible_color(510)","'green'",[c("violet","visible_color(400)","'violet'"),c("green","visible_color(510)","'green'"),c("infrared","visible_color(800)","None")],["ranges","light"]),
s("2.22","radiation_band","Electromagnetic Frequency Band",[a("frequency_hz","float","Frequency in hertz.")],"str","Name an electromagnetic radiation band.","Use radio below 3e9, microwave below 3e12, infrared below 4.3e14, visible below 7.5e14, ultraviolet below 3e17, X-ray below 3e19, and gamma ray otherwise.","radiation_band(5e14)","'visible light'",[c("radio","radiation_band(1e6)","'radio waves'"),c("visible","radiation_band(5e14)","'visible light'"),c("gamma","radiation_band(1e20)","'gamma rays'")],["scientific notation","ranges"]),
s("2.23","phone_bill","Cell Phone Bill",[a("minutes","int","Monthly call minutes."),a("texts","int","Monthly text messages.")],"dict[str, float]","Calculate and itemize a monthly mobile-phone bill.","The base charge is $15 for 50 minutes and 50 texts. Extra minutes cost $0.25 and extra texts cost $0.15. Add a $0.44 emergency fee, then apply 5 percent tax to the entire pre-tax bill. Return base, extra_minutes, extra_texts, emergency_fee, tax, and total, each rounded to cents.","phone_bill(60, 55)","an itemized dictionary totalling $19.62",[c("within plan","phone_bill(40,40)","{'base':15.0,'extra_minutes':0.0,'extra_texts':0.0,'emergency_fee':0.44,'tax':0.77,'total':16.21}"),c("overages","phone_bill(60,55)","{'base':15.0,'extra_minutes':2.5,'extra_texts':0.75,'emergency_fee':0.44,'tax':0.93,'total':19.62}"),c("minutes only","phone_bill(52,50)","{'base':15.0,'extra_minutes':0.5,'extra_texts':0.0,'emergency_fee':0.44,'tax':0.8,'total':16.74}")],["billing","conditionals","rounding"],"Intermediate"),
s("2.24","is_leap_year","Leap Year",[a("year","int","Gregorian calendar year.")],"bool","Determine whether a year is a Gregorian leap year.","A year is a leap year when divisible by 400, or divisible by 4 but not by 100.","is_leap_year(2000)","True",[c("divisible by 400","is_leap_year(2000)","True"),c("century","is_leap_year(1900)","False"),c("ordinary leap year","is_leap_year(2024)","True")],["boolean logic","calendar"]),
s("2.25","next_date","Next Calendar Date",[a("year","int","Current year."),a("month","int","Current month."),a("day","int","Current day.")],"tuple[int, int, int]","Calculate the calendar date following a valid date.","Respect each month's length and February leap years. Roll month and year forward when needed.","next_date(2024, 2, 28)","(2024, 2, 29)",[c("ordinary day","next_date(2023,5,10)","(2023,5,11)"),c("leap February","next_date(2024,2,28)","(2024,2,29)"),c("new year","next_date(2023,12,31)","(2024,1,1)")],["calendar","nested conditionals"],"Advanced"),
s("2.26","valid_license_plate","License Plate Validator",[a("plate","str","Plate text without spaces.")],"bool","Validate an old or new Canadian-style license plate.","An old plate has exactly three uppercase letters followed by three digits. A new plate has four digits followed by three uppercase letters.","valid_license_plate('ABC123')","True",[c("old style","valid_license_plate('ABC123')","True"),c("new style","valid_license_plate('1234ABC')","True"),c("invalid","valid_license_plate('AB1234')","False")],["string validation","patterns"]),
s("2.27","roulette_spin","Roulette Payout Simulation",[a("seed","int | None","Optional seed for a reproducible spin.","None")],"tuple[str, list[str]]","Simulate one American roulette spin and list every winning bet category.","Use a local random.Random(seed) to select one of 38 equally likely pockets: 0, 00, and 1 through 36. The payout list always includes the selected pocket. For 1-36 also include red/black, odd/even, and 1-18/19-36. Red numbers are 1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36; the remaining numbered pockets are black. Zero pockets have no outside payouts.","roulette_spin(seed=1)","(selected pocket, all winning categories)",[c("repeatable","roulette_spin(4)==roulette_spin(4)","True"),c("valid pocket","roulette_spin(2)[0] in ['0','00']+[str(n) for n in range(1,37)]","True"),c("straight bet included","(lambda r: r[0] in r[1])(roulette_spin(8))","True"),c("zero rules","all(len(bets)==1 for seed in range(100) for pocket,bets in [roulette_spin(seed)] if pocket in ('0','00'))","True")],["random simulation","membership","multiple conditions"],"Advanced",("import random",)),
]

LOOPS = [
s("3.1","average_until_zero","Average Until Zero",[a("values","list[float]","Values ending at the first zero sentinel.")],"float | None","Average values appearing before a zero sentinel.","Ignore everything after the first zero. Return None when zero is the first value.","average_until_zero([4, 6, 0])","5.0",[c("several","average_until_zero([4,6,0])","5.0"),c("empty","average_until_zero([0])","None"),c("stops","average_until_zero([2,0,100])","2.0")],["sentinel","average","loops"]),
s("3.2","discount_table","Discount Table",[a("prices","list[float]","Original prices."),a("rate","float","Discount rate as a decimal.","0.60")],"list[tuple[float, float, float]]","Build rows for a sale-price table.","For each price return original price, discount, and reduced price, rounded to two decimals.","discount_table([4.95])","[(4.95, 2.97, 1.98)]",[c("one","discount_table([4.95])","[(4.95,2.97,1.98)]"),c("two","discount_table([10,20])","[(10,6.0,4.0),(20,12.0,8.0)]"),c("empty","discount_table([])","[]")],["loops","currency"]),
s("3.3","temperature_table","Temperature Table",[],"list[tuple[int, float]]","Create a Celsius-to-Fahrenheit table.","Return rows for Celsius 0 through 100 in steps of 10 using F=C*9/5+32.","temperature_table()","[(0, 32.0), ..., (100, 212.0)]",[c("row count","len(temperature_table())","11"),c("first","temperature_table()[0]","(0,32.0)"),c("last","temperature_table()[-1]","(100,212.0)")],["range","loops","conversion"]),
s("3.4","cash_total","Cash Purchase Rounding",[a("prices","list[float]","Individual purchase prices.")],"tuple[float, float]","Calculate electronic and cash totals for purchases.","Sum prices, round the electronic total to cents, and round the cash total to the nearest $0.05 because pennies are unavailable.","cash_total([1.02, 2.01])","(3.03, 3.05)",[c("round up","cash_total([1.02,2.01])","(3.03,3.05)"),c("exact nickel","cash_total([2.0,3.05])","(5.05,5.05)"),c("empty","cash_total([])","(0.0,0.0)")],["accumulation","rounding","currency"]),
s("3.5","polygon_perimeter","Polygon Perimeter",[a("points","list[tuple[float, float]]","Polygon vertices in boundary order.")],"float","Calculate the perimeter of a polygon.","Add Euclidean distances between consecutive points and close the polygon from the final point back to the first. At least three points are supplied.","polygon_perimeter([(0,0),(3,0),(3,4)])","12.0",[c("triangle","polygon_perimeter([(0,0),(3,0),(3,4)])","12.0",True),c("unit square","polygon_perimeter([(0,0),(1,0),(1,1),(0,1)])","4.0",True),c("rectangle","polygon_perimeter([(0,0),(2,0),(2,1),(0,1)])","6.0",True)],["geometry","distance","loops"],"Intermediate",("import math",)),
s("3.6","grade_point_average","Grade Point Average",[a("grades","list[str]","Letter grades to average.")],"float | None","Calculate the mean grade-point value.","Use the standard mapping from the grade conversion exercise, including A+=4.0 and F=0.0. Return None for an empty list and raise ValueError for unsupported grades.","grade_point_average(['A','B+','C'])","3.1",[c("mixed","grade_point_average(['A','B+','C'])","3.1",True),c("empty","grade_point_average([])","None"),c("all A","grade_point_average(['A','A-'])","3.85",True)],["averages","lookup","loops"],raises=(("ValueError","If a grade is unsupported."),)),
s("3.7","admission_total","Admission Price",[a("ages","list[int]","Ages of all guests.")],"float","Calculate admission for a group.","Guests age 2 and under are free; ages 3-12 cost $14; ages 65 and over cost $18; everyone else costs $23.","admission_total([2,10,30,70])","55.0",[c("mixed group","admission_total([2,10,30,70])","55.0"),c("children","admission_total([1,2,3])","14.0"),c("empty","admission_total([])","0.0")],["accumulation","age ranges"]),
s("3.8","append_parity_bits","Even Parity Bits",[a("groups","list[str]","Eight-bit binary strings.")],"list[str]","Append an even-parity bit to binary groups.","For each eight-bit group append 0 when it already contains an even number of 1 bits, otherwise append 1 so the resulting nine bits have even parity.","append_parity_bits(['10101010'])","['101010100']",[c("even ones","append_parity_bits(['10101010'])","['101010100']"),c("odd ones","append_parity_bits(['10000000'])","['100000001']"),c("several","append_parity_bits(['00000000','11111111'])","['000000000','111111110']")],["binary","counting","loops"]),
s("3.9","pi_approximations","Successive Pi Approximations",[a("count","int","Number of approximations to produce.","15")],"list[float]","Generate successive approximations of pi from an alternating series.","The first approximation is 3. For n starting at 1, add or subtract 4 / ((2n)*(2n+1)*(2n+2)), alternating plus then minus. Return count cumulative approximations so each entry includes one more term than the previous entry.","pi_approximations(3)","[3.0, 3.166666..., 3.133333...]",[c("first term","pi_approximations(1)","[3.0]"),c("three terms","pi_approximations(3)","[3.0,3.1666666666666665,3.1333333333333333]"),c("default count","len(pi_approximations())","15")],["series","alternating signs","loops"]),
s("3.10","caesar_cipher","Caesar Cipher",[a("text","str","Text to transform."),a("shift","int","Alphabet rotation amount.")],"str","Apply a Caesar rotation to letters in text.","Rotate uppercase and lowercase letters independently with wraparound. Preserve spaces, digits, and punctuation unchanged. Negative shifts decode.","caesar_cipher('Hello!', 3)","'Khoor!'",[c("encode","caesar_cipher('Hello!',3)","'Khoor!'"),c("wrap","caesar_cipher('xyz',3)","'abc'"),c("decode","caesar_cipher('Khoor',-3)","'Hello'")],["strings","modulo","loops"]),
s("3.11","newton_sqrt","Square Root with Newton's Method",[a("number","float","Non-negative value whose square root is required."),a("tolerance","float","Maximum allowed value of abs(guess*guess-number).","1e-12")],"float","Approximate a square root by repeatedly improving a guess.","Follow Newton's method explicitly: for positive number, initialize guess to number/2. While abs(guess*guess-number) is greater than tolerance, replace guess with the average of guess and number/guess. Return the first guess that is good enough. Handle number=0 directly to avoid division by zero.","newton_sqrt(2)","approximately 1.41421356237",[c("two","newton_sqrt(2)","1.4142135623730951",True),c("perfect square","newton_sqrt(81)","9.0",True),c("zero","newton_sqrt(0)","0.0",True)],["while loops","Newton's method","tolerance"]),
s("3.12","is_palindrome","Palindrome",[a("text","str","Case-sensitive text to inspect.")],"bool","Check whether text reads identically forward and backward.","Compare characters from opposite ends or compare with a reversed copy. This version is case-sensitive and does not remove punctuation.","is_palindrome('racecar')","True",[c("palindrome","is_palindrome('racecar')","True"),c("not palindrome","is_palindrome('python')","False"),c("empty","is_palindrome('')","True")],["strings","reversal"]),
s("3.13","is_phrase_palindrome","Phrase Palindrome",[a("text","str","Phrase to normalize and inspect.")],"bool","Check whether a phrase is a palindrome after normalization.","Keep only letters and digits, convert to lowercase, then compare the result with its reversal.","is_phrase_palindrome('A man, a plan, a canal: Panama!')","True",[c("classic phrase","is_phrase_palindrome('A man, a plan, a canal: Panama!')","True"),c("ordinary text","is_phrase_palindrome('Not one')","False"),c("punctuation only","is_phrase_palindrome('!!!')","True")],["normalization","palindromes"]),
s("3.14","multiplication_table","Multiplication Table",[a("size","int","Largest row and column factor.","10")],"list[list[int]]","Create a square multiplication table.","Return size rows; row r contains r*c for columns 1 through size, with both indices starting at 1.","multiplication_table(3)","[[1,2,3],[2,4,6],[3,6,9]]",[c("three","multiplication_table(3)","[[1,2,3],[2,4,6],[3,6,9]]"),c("one","multiplication_table(1)","[[1]]"),c("empty","multiplication_table(0)","[]")],["nested loops","tables"]),
s("3.15","iterative_gcd","Greatest Common Divisor",[a("a","int","First positive integer."),a("b","int","Second positive integer.")],"int","Find the largest integer that divides two positive integers evenly.","Use this required search algorithm: initialize candidate to min(a,b), then repeatedly decrease candidate by 1 while it fails to divide either input evenly. Return the first candidate that divides both.","iterative_gcd(48, 18)","6",[c("common example","iterative_gcd(48,18)","6"),c("coprime","iterative_gcd(17,5)","1"),c("one divides other","iterative_gcd(12,36)","12")],["while loops","divisibility","search"]),
s("3.16","prime_factors","Prime Factors",[a("number","int","Integer at least 2.")],"list[int]","Factor an integer into prime factors.","Repeatedly divide by the smallest possible factor, appending it each time, until the remaining value is 1. Preserve repeated factors.","prime_factors(72)","[2,2,2,3,3]",[c("composite","prime_factors(72)","[2,2,2,3,3]"),c("prime","prime_factors(13)","[13]"),c("power","prime_factors(16)","[2,2,2,2]")],["factorization","loops"]),
s("3.17","binary_to_decimal","Binary to Decimal",[a("binary","str","Non-empty string containing only 0 and 1.")],"int","Convert a binary string to a decimal integer.","Process digits left to right, doubling the accumulated value before adding the next bit. Do not call int(binary, 2).","binary_to_decimal('10110')","22",[c("sample","binary_to_decimal('10110')","22"),c("zero","binary_to_decimal('0')","0"),c("one byte","binary_to_decimal('11111111')","255")],["binary","place value","loops"]),
s("3.18","decimal_to_binary","Decimal to Binary",[a("number","int","Non-negative decimal integer.")],"str","Convert a decimal integer to binary text.","Repeatedly divide by 2 and collect remainders, then reverse them. Return '0' for zero and do not use bin().","decimal_to_binary(22)","'10110'",[c("sample","decimal_to_binary(22)","'10110'"),c("zero","decimal_to_binary(0)","'0'"),c("byte maximum","decimal_to_binary(255)","'11111111'")],["binary","division","loops"]),
s("3.19","maximum_experiment","Maximum Integer Simulation",[a("seed","int | None","Optional seed for reproducible random values.","None"),a("count","int","Number of random integers to generate.","100")],"tuple[list[tuple[int, bool]], int, int]","Simulate the process of discovering new maximum values.","Use a local random.Random(seed) to generate count integers from 1 through 100. Mark the first value as the initial maximum but do not count it as an update. For each later value, mark whether it establishes a strictly larger maximum. Return all (value,is_new_maximum) records, the final maximum, and the number of later updates.","maximum_experiment(seed=1, count=5)","five marked values, final maximum, update count",[c("count and range","(lambda r: len(r[0])==100 and all(1<=v<=100 for v,_ in r[0]))(maximum_experiment(1))","True"),c("repeatable","maximum_experiment(7,10)==maximum_experiment(7,10)","True"),c("summary matches records","(lambda r: r[1]==max(v for v,_ in r[0]) and r[2]==sum(flag for _,flag in r[0][1:]))(maximum_experiment(3,20))","True")],["random simulation","maximum","state tracking"],"Intermediate",("import random",)),
s("3.20","coin_flip_experiment","Coin-Flip Simulation",[a("trials","int","Number of independent streak simulations.","10"),a("seed","int | None","Optional seed for reproducible flips.","None")],"tuple[list[tuple[str, int]], float]","Simulate fair coin flips until three equal outcomes occur consecutively.","For each trial, use a local random.Random(seed) stream to generate H or T with equal probability until HHH or TTT first appears. Record the complete outcome string and its flip count. Return all trial records and the average count. By default, perform 10 independent simulations.","coin_flip_experiment(3, seed=1)","three outcome/count records and their average",[c("ten trials","len(coin_flip_experiment(seed=1)[0])","10"),c("valid streak endings","all(text.endswith('HHH') or text.endswith('TTT') for text,_ in coin_flip_experiment(5,2)[0])","True"),c("repeatable","coin_flip_experiment(4,7)==coin_flip_experiment(4,7)","True")],["random simulation","runs","averages"],"Intermediate",("import random",)),
]

FUNCTIONS = [
s("4.1","hypotenuse","Compute the Hypotenuse",[a("a","float","First perpendicular side."),a("b","float","Second perpendicular side.")],"float","Calculate a right triangle's hypotenuse.","Use sqrt(a^2+b^2) for non-negative side lengths.","hypotenuse(3,4)","5.0",[c("3-4-5","hypotenuse(3,4)","5.0",True),c("unit legs","hypotenuse(1,1)","1.4142135623730951",True),c("zero leg","hypotenuse(0,5)","5.0",True)],["functions","geometry"],imports=("import math",)),
s("4.2","taxi_fare","Taxi Fare",[a("distance_km","float","Trip distance in kilometres.")],"float","Calculate a taxi fare from trip distance.","Charge a $4.00 base fare plus $0.25 for each started 140 metres. Round to cents.","taxi_fare(1.0)","6.0",[c("one kilometre","taxi_fare(1.0)","6.0"),c("short ride","taxi_fare(0.14)","4.25"),c("zero","taxi_fare(0)","4.0")],["functions","ceiling","currency"],imports=("import math",)),
s("4.3","shipping_charge","Shipping Calculator",[a("items","int","Positive item count.")],"float","Calculate shipping for an order.","The first item costs $10.95 to ship and each additional item costs $2.95. Round to cents.","shipping_charge(3)","16.85",[c("one","shipping_charge(1)","10.95"),c("three","shipping_charge(3)","16.85"),c("ten","shipping_charge(10)","37.5")],["functions","piecewise cost"]),
s("4.4","median_three","Median of Three",[a("a","float","First value."),a("b","float","Second value."),a("c","float","Third value.")],"float","Return the middle of three numeric values.","The median is neither strictly smallest nor strictly largest; preserve duplicates correctly.","median_three(9,2,5)","5",[c("mixed","median_three(9,2,5)","5"),c("duplicates","median_three(4,4,1)","4"),c("negative","median_three(-1,-5,3)","-1")],["functions","ordering"]),
s("4.5","ordinal","Ordinal Number",[a("number","int","Integer to represent.")],"str","Convert an integer from 1 through 12 to an ordinal word.","Return first through twelfth for supported values and an empty string otherwise.","ordinal(3)","'third'",[c("first","ordinal(1)","'first'"),c("twelfth","ordinal(12)","'twelfth'"),c("unsupported","ordinal(13)","''")],["functions","lookup"]),
s("4.6","twelve_days_verse","Twelve Days Verse",[a("day","int","Verse number from 1 through 12.")],"str","Build one verse of The Twelve Days of Christmas.","Begin with 'On the {ordinal} day of Christmas my true love sent to me:' and include gifts from day down to first, joining lines with newline characters. Use 'and a Partridge in a Pear Tree.' when day is greater than one.","twelve_days_verse(1)","first verse text",[c("first heading","twelve_days_verse(1).startswith('On the first day')","True"),c("third gifts","'Three French Hens' in twelve_days_verse(3)","True"),c("cumulative","'Two Turtle Doves' in twelve_days_verse(12)","True")],["functions","lists","formatting"],"Intermediate"),
s("4.7","center_text","Center Text",[a("text","str","Text to center."),a("width","int","Total terminal width.","80")],"str","Center text within a fixed-width terminal line.","Add floor((width-len(text))/2) leading spaces. If text is at least width characters, return it unchanged.","center_text('hello', 11)","'   hello'",[c("odd padding","center_text('hello',11)","'   hello'"),c("even padding","center_text('test',10)","'   test'"),c("too long","center_text('long text',4)","'long text'")],["functions","string formatting"]),
s("4.8","valid_triangle","Valid Triangle",[a("a","float","First side length."),a("b","float","Second side length."),a("c","float","Third side length.")],"bool","Check whether three lengths can form a triangle.","All lengths must be positive and each side must be shorter than the sum of the other two.","valid_triangle(3,4,5)","True",[c("valid","valid_triangle(3,4,5)","True"),c("degenerate","valid_triangle(1,2,3)","False"),c("negative","valid_triangle(-1,4,4)","False")],["functions","geometry","validation"]),
s("4.9","capitalize_sentences","Capitalize It",[a("text","str","Text to correct.")],"str","Apply basic sentence capitalization to text.","Capitalize the first alphabetic character, the first alphabetic character after '.', '!', or '?', and standalone lowercase i. Preserve all other characters.","capitalize_sentences('hello. i am here!')","'Hello. I am here!'",[c("sentences","capitalize_sentences('hello. i am here!')","'Hello. I am here!'"),c("question","capitalize_sentences('why? because.')","'Why? Because.'"),c("empty","capitalize_sentences('')","''")],["functions","text processing","state"]),
s("4.10","represents_integer","Integer String",[a("text","str","Candidate integer text, possibly surrounded by whitespace.")],"bool","Check whether text represents a base-10 integer.","Ignore leading and trailing whitespace first. The remaining text is valid when it contains one or more digits, optionally preceded by exactly one + or - sign. Reject a sign without digits, decimal points, internal spaces, and other characters.","represents_integer('  -42  ')","True",[c("negative with whitespace","represents_integer('  -42  ')","True"),c("positive sign","represents_integer('+7')","True"),c("decimal","represents_integer('3.5')","False")],["functions","validation","strings"]),
s("4.11","operator_precedence","Operator Precedence",[a("operator","str","Operator token.")],"int","Return a precedence level for a mathematical operator.","Return 1 for + and -, 2 for * and /, 3 for ^, and -1 for unrecognized operators.","operator_precedence('*')","2",[c("addition","operator_precedence('+')","1"),c("power","operator_precedence('^')","3"),c("unknown","operator_precedence('%')","-1")],["functions","operators"]),
s("4.12","is_prime","Prime Number",[a("number","int","Integer to test.")],"bool","Determine whether an integer is prime.","Numbers below 2 are not prime. Test possible divisors only through the square root of number.","is_prime(29)","True",[c("prime","is_prime(29)","True"),c("composite","is_prime(35)","False"),c("below two","is_prime(1)","False")],["functions","primes","optimization"]),
s("4.13","next_prime","Next Prime",[a("number","int","Starting integer.")],"int","Find the first prime strictly greater than a number.","Test consecutive integers with prime-number logic until one is prime.","next_prime(29)","31",[c("after prime","next_prime(29)","31"),c("after composite","next_prime(14)","17"),c("negative start","next_prime(-5)","2")],["functions","primes","loops"]),
s("4.14","random_password","Random Password",[a("seed","int | None","Optional deterministic seed.","None")],"str","Generate a random ASCII password.","Use a local random.Random(seed). Choose a length from 7 through 10 and characters with ASCII codes 33 through 126.","random_password(1)","deterministic printable password",[c("valid length","7 <= len(random_password(1)) <= 10","True"),c("printable","all(33 <= ord(ch) <= 126 for ch in random_password(2))","True"),c("repeatable","random_password(5) == random_password(5)","True")],["functions","randomness","ASCII"],imports=("import random",)),
s("4.15","random_license_plate","Random License Plate",[a("seed","int | None","Optional deterministic seed.","None")],"str","Generate a random old- or new-style license plate.","Use a local random.Random(seed). Randomly choose either three uppercase letters plus three digits, or four digits plus three uppercase letters.","random_license_plate(1)","a valid deterministic plate",[c("valid shape","len(random_license_plate(1)) in (6,7)","True"),c("repeatable","random_license_plate(3) == random_license_plate(3)","True"),c("pattern","(lambda p: (len(p)==6 and p[:3].isalpha() and p[3:].isdigit()) or (len(p)==7 and p[:4].isdigit() and p[4:].isalpha()))(random_license_plate(8))","True")],["functions","randomness","strings"],imports=("import random",)),
s("4.16","is_good_password","Password Strength",[a("password","str","Password to assess.")],"bool","Check whether a password meets basic strength requirements.","A good password contains at least eight characters, at least one uppercase letter, at least one lowercase letter, and at least one digit.","is_good_password('PyLab2026')","True",[c("good","is_good_password('PyLab2026')","True"),c("too short","is_good_password('Py1')","False"),c("missing digit","is_good_password('LongPassword')","False")],["functions","validation","any"]),
s("4.17","random_good_password","Random Good Password",[a("seed","int | None","Optional deterministic seed.","None")],"tuple[str, int]","Generate random passwords until one passes the strength checker.","Use one local random.Random(seed) stream. Each attempt creates a 7-10 character password from ASCII positions 33-126. A successful password has at least eight characters, one uppercase letter, one lowercase letter, and one digit. Continue until all four conditions hold, then return both the password and the number of attempts.","random_good_password(1)","(a deterministic strong password, attempt_count)",[c("strong","(lambda r: len(r[0])>=8 and any(x.isupper() for x in r[0]) and any(x.islower() for x in r[0]) and any(x.isdigit() for x in r[0]) and r[1]>=1)(random_good_password(1))","True"),c("repeatable","random_good_password(4) == random_good_password(4)","True"),c("printable","all(33 <= ord(ch) <= 126 for ch in random_good_password(7)[0])","True")],["functions","randomness","validation"],"Intermediate",("import random",)),
s("4.18","convert_hex_digit","Hexadecimal and Decimal Digits",[a("value","str | int","Single hexadecimal digit or decimal value 0-15.")],"int | str","Convert one digit between hexadecimal and decimal forms.","Support both conversion directions through one typed interface: a one-character string 0-9 or A-F (case-insensitive) returns its integer value, while an integer 0-15 returns one uppercase hexadecimal digit. Raise ValueError otherwise.","convert_hex_digit('B')","11",[c("hex to int","convert_hex_digit('B')","11"),c("lowercase","convert_hex_digit('f')","15"),c("int to hex","convert_hex_digit(12)","'C'")],["functions","hexadecimal","validation"],raises=(("ValueError","If value is outside the supported single-digit range."),)),
s("4.19","convert_base","Arbitrary Base Conversion",[a("text","str","Number text in the source base."),a("source_base","int","Base used by text, from 2 through 16."),a("target_base","int","Desired base, from 2 through 16.")],"str","Convert a non-negative integer between bases 2 through 16.","Use digits 0-9 and A-F. Convert through a decimal accumulator without int(text, base) or built-in formatting. Return uppercase digits.","convert_base('FF',16,2)","'11111111'",[c("hex to binary","convert_base('FF',16,2)","'11111111'"),c("binary to decimal","convert_base('10110',2,10)","'22'"),c("zero","convert_base('0',8,16)","'0'")],["functions","base conversion","loops"],"Advanced"),
s("4.20","days_in_month","Days in a Specific Month",[a("month","int","Month number from 1 through 12."),a("year","int","Gregorian year.")],"int","Return the exact number of days in a month and year.","Use 31- and 30-day month groups and apply Gregorian leap-year rules to February.","days_in_month(2,2024)","29",[c("leap February","days_in_month(2,2024)","29"),c("ordinary February","days_in_month(2,2023)","28"),c("April","days_in_month(4,2024)","30")],["functions","calendar","leap years"]),
s("4.21","reduce_fraction","Reduce a Fraction",[a("numerator","int","Fraction numerator."),a("denominator","int","Non-zero fraction denominator.")],"tuple[int, int]","Reduce a fraction to lowest terms.","Divide numerator and denominator by their greatest common divisor. Keep the denominator positive and preserve a zero numerator as 0/1.","reduce_fraction(42,56)","(3,4)",[c("common factor","reduce_fraction(42,56)","(3,4)"),c("negative denominator","reduce_fraction(1,-2)","(-1,2)"),c("zero numerator","reduce_fraction(0,5)","(0,1)")],["functions","GCD","fractions"]),
s("4.22","reduce_measures","Reduce Recipe Measures",[a("amount","int","Non-negative count of the supplied unit."),a("unit","str","'cup', 'tablespoon', or 'teaspoon'.")],"str","Express an imperial recipe volume using the largest practical units.","Convert amount and unit to teaspoons using 1 tablespoon=3 teaspoons and 1 cup=16 tablespoons. Then convert back to the largest units and return a natural-language string that omits zero-valued units and uses correct singular/plural labels.","reduce_measures(59, 'teaspoon')","'1 cup, 3 tablespoons, 2 teaspoons'",[c("worked example","reduce_measures(59,'teaspoon')","'1 cup, 3 tablespoons, 2 teaspoons'"),c("tablespoons","reduce_measures(16,'tablespoon')","'1 cup'"),c("small amount","reduce_measures(2,'teaspoon')","'2 teaspoons'")],["functions","division","formatting"],"Intermediate"),
s("4.23","is_magic_date","Magic Dates",[a("year","int","Four-digit year."),a("month","int","Month number."),a("day","int","Day of month.")],"bool","Determine whether a date is mathematically magic.","A date is magic when day multiplied by month equals the final two digits of year; June 10, 1960 qualifies because 6*10=60. Implement this predicate first. A complete program can then combine it with a days-in-month function to examine every valid date from 1901 through 2000 and display all matches.","is_magic_date(1960,6,10)","True",[c("worked example","is_magic_date(1960,6,10)","True"),c("another magic","is_magic_date(2024,4,6)","True"),c("ordinary","is_magic_date(2023,4,6)","False")],["functions","dates","modulo"]),
]

CHAPTERS={"conditionals":("Conditionals","conditionals.json",CONDITIONALS),"loops":("Loops","loops.json",LOOPS),"functions":("Functions","functions.json",FUNCTIONS)}

def signature(x):
 parts=[]
 for name,type_,_,default in x["args"]:
  parts.append(f"{name}: {type_}"+(f" = {default}" if default is not None else ""))
 return f"def {x['slug']}({', '.join(parts)}) -> {x['ret']}:"

def starter(x):
 lines=list(x["imports"])
 if lines: lines.append("")
 lines += [signature(x),f"    \"\"\"{x['summary']}"]
 if x["args"]:
  lines += ["","    Args:"]+[f"        {n} ({t}): {d}" for n,t,d,_ in x["args"]]
 lines += ["","    Returns:",f"        {x['ret']}: {x['summary']}"]
 if x["raises"]: lines += ["","    Raises:"]+[f"        {k}: {d}" for k,d in x["raises"]]
 lines += ['    """',"    pass",""]
 return "\n".join(lines)

def build(section_id,category,x):
 tests=[]
 for name,call,expected,approx in x["cases"]:
  code=(f"actual={call}\nexpected={expected}\nassert abs(actual-expected)<1e-9" if approx else f"assert {call} == {expected}")
  tests.append({"name":name,"stdin":"","moduleMode":True,"code":code})
 parameter_lines = "\n".join(f"• {name} ({type_}): {description}" for name,type_,description,_ in x["args"])
 if not parameter_lines: parameter_lines = "• This function does not require arguments."
 prompt = (
  f"{x['summary']}\n\n"
  f"Background and required method:\n{x['rules']}\n\n"
  f"Implement this interface:\n{signature(x)}\n\n"
  f"Parameters:\n{parameter_lines}"
 )
 return {"id":f"{section_id}-{x['slug'].replace('_','-')}","number":x["number"],"title":x["title"],"category":category,"difficulty":x["difficulty"],"prompt":prompt,"signature":signature(x),"concepts":x["concepts"],"examples":[{"input":x["example"],"output":x["output"]}],"starterFiles":[{"name":"main.py","content":starter(x)}],"tests":tests}

def main():
 core_path=ROOT/"problems/problems.json"; core=json.loads(core_path.read_text())
 for section_id,(category,filename,specs) in CHAPTERS.items():
  items=[build(section_id,category,x) for x in specs]
  for p in items:
   ast.parse(p["starterFiles"][0]["content"])
   for t in p["tests"]: ast.parse(t["code"])
  (ROOT/"problems"/filename).write_text(json.dumps({"version":1,"problems":items},indent=2,ensure_ascii=False)+"\n")
  section=next(s for s in core["sections"] if s["id"]==section_id)
  section["problems"]=[{"number":p["number"],"title":p["title"],"id":p["id"]} for p in items]
 core_path.write_text(json.dumps(core,indent=2,ensure_ascii=False)+"\n")
 from add_advanced_boundary_tests import main as add_advanced_boundary_tests
 add_advanced_boundary_tests()

if __name__=="__main__": main()
